{% set version = '0.8.1' %}
{% set name = 'gfx-portability' %}
{% set repo_name = 'portability' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gfx-rs/{{ repo_name }}/archive/{{ version }}.tar.gz
  sha256: 1ca8a254c124e5396f2011d553468cfe24f0970d17fb3d7f60a09d086b189d38

build:
  number: 0
  script:
    - set RUST_BACKTRACE=1  # [win]
    - cargo build --release -v
    - $STRIP -S target/release/*${SHLIB_EXT}  # [not win]
    - mkdir $PREFIX/bin  # [not win]
    - mkdir $PREFIX/lib  # [not win]
    - mkdir %LIBRARY_BIN%  # [win]
    - mkdir %LIBRARY_LIB%  # [win]
    - cp -rf target/release/*${SHLIB_EXT} $PREFIX/bin  # [not win]
    - cp target/release/libportability.a $PREFIX/lib  # [not win]
    - ln -s target/release/libportability${SHLIB_EXT} libvulkan${SHLIB_EXT}  # [not win]
    - copy target\release\*%SHLIB_EXT% %LIBRARY_BIN%  # [win]
    - copy target\release\portability%SHLIB_EXT% %LIBRARY_BIN%\vulkan-1%SHLIB_EXT%  # [win]
    - copy target\release\libportability* %LIBRARY_LIB%\  # [win]
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib

requirements:
  build:
    - {{ compiler('rust') }}

about:
  home: https://github.com/gfx-rs/portability
  license: MPL-2.0
  license_family: Mozilla
  license_file: LICENSE
  summary: Prototype library implementing Vulkan Portability Initiative
  doc_url: https://github.com/gfx-rs/portability
  dev_url: https://github.com/gfx-rs/portability

extra:
  recipe-maintainers:
    - mingwandroid
