{% set name = 'rstudio' %}
{% set version = '1.3.1056' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/rstudio/rstudio.git
  git_ref: v{{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - git
    - cmake

  host:
    - r-base
