{% set name = "java-config" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/SpatialInteractive/java-config
  patches:
   - 0001-Debug-System.getProperties.patch

build:
  number: 0

requirements:
  build:
    - git            # [not win]
    - m2-git         # [win]
    - m2-filesystem  # [win]

about:
  home: https://github.com/SpatialInteractive/java-config
  license: Unknown
  license_family: Other
  summary: 'The missing package config program for java installations'
  description: |
    Java configuration option command line tool. This does for java what
    similar tools for packages such as freetype (freetype-config) provide.
    I wrote this so that I could find what I needed quickly to build JNI
    libraries for all unixish platforms.

    Copy the java-config.jar file into your project. Run it as
    `java -jar java-config.jar` with the correct java executable and it
    will report vital statistics about your installation including cflags
    and ldflags for jni linking.
  dev_url: https://github.com/SpatialInteractive/java-config
  doc_url: https://github.com/SpatialInteractive/java-config/blob/master/README.markdown
  doc_source_url: https://github.com/SpatialInteractive/java-config/blob/master/README.markdown

extra:
  recipe-maintainers:
    - mingwandroid
