CONDA_BUILD_SYSROOT:  # [osx]
  - /opt/MacOSX10.11.sdk  # [osx]
macos_min_version:  # [osx]
  - 10.11  # [osx]
macos_machine:  # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.11  # [osx]
