{% set name = "squashfskit" %}
{% set version = "4.14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #- url: https://github.com/squashfskit/squashfskit/archive/v{{ version }}.tar.gz
  #  fn: {{ name }}-v{{ version }}.tar.gz
  #  sha256: 10ad288a4743a22ec69bd04bb5633b29072e4646c0062fd484e82ef247669dc7
  - git_url: https://github.com/squashfskit/squashfskit
    patches:
      - 0001-macOS-fixes.patch
      - 0002-Fix-https-github.com-squashfskit-squashfskit-issues-.patch
  - url: https://raw.githubusercontent.com/plougher/squashfs-tools/master/COPYING
    sha256: 8177f97513213526df2cf6184d8ff986c675afb514d4e68a404010521b880643


build:
  number: 0
  skip: True  # [win]


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - xz
    - lz4-c
    - lzo
    - zstd

test:
  files:
    - random_binaries/
  commands:
    # --help fails
    - unsquashfs --help || true
    - mksquashfs --help || true
    # grep for the (gold) zstandard
    - unsquashfs --help 2>&1 | grep zstd
    - mksquashfs --help 2>&1 | grep zstd
    - mksquashfs random_binaries/* squashed_fs.img
    - unsquashfs -d random_binaries2 squashed_fs.img
    - find random_binaries2
    - diff -urN random_binaries random_binaries2

#    - unsquashfs /opt/sw/OSes/SquashFSes/SYSTEM.LibreELEC-RPi4.arm-9.1.001
#    # Test reproducibility
#    - rm squashfs-root/usr/cache/shadow
#    - mksquashfs squashfs-root SYSTEM.LibreELEC-RPi4.arm-9.1.001.1
#    - mksquashfs squashfs-root SYSTEM.LibreELEC-RPi4.arm-9.1.001.2
#    - shasum -a 256 SYSTEM.LibreELEC-RPi4.arm-9.1.001.1
#    - shasum -a 256 SYSTEM.LibreELEC-RPi4.arm-9.1.001.2

about:
  # Maybe:
  # home: https://packages.debian.org/sid/squashfs-tools
  home: https://github.com/plougher/squashfs-tools
  license: GPL-2.0
  license_file: COPYING
  summary: tools to create and extract Squashfs filesystems ({Rasp,De}bian)
  description: |
    tools to create and extract Squashfs filesystems
    with Debian patches and good compression support (only LZMA unsupported)
  dev_url: https://github.com/plougher/squashfs-tools

extra:
  recipe-maintainers:
    - mingwandroid
    # I took the liberty here, @jjhelmus, let me know if you are not up for it.
    - jjhelmus
